// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaDeViajes.Entities
{
    public partial class tbSucursalesPorEmpleados
    {
        public int suem_Id { get; set; }
        public int sucu_Id { get; set; }
        public int empl_Id { get; set; }
        public int suem_Kilometros { get; set; }
        public string suem_Direccion { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime suem_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? suem_FechaModificacion { get; set; }
        public bool? suem_Estado { get; set; }

        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
    }
}