// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaDeViajes.Entities
{
    public partial class tbViajes
    {
        public int viaj_Id { get; set; }
        public DateTime viaj_FechaViaje { get; set; }
        public int empl_Id { get; set; }
        public int tran_Id { get; set; }
        public int usua_UsuarioCreacion { get; set; }
        public DateTime viaj_FechaCreacion { get; set; }
        public int? usua_UsuarioModificacion { get; set; }
        public DateTime? viaj_FechaModificacion { get; set; }
        public bool? viaj_Estado { get; set; }

        public virtual tbUsuarios usua_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuarioModificacionNavigation { get; set; }
    }
}